version: '2'
services:
  rpma:
    build: .
    restart: always
    container_name: rpma
    links:
      - mongo
    ports:
      - "3001:3001"
    environment:
          - "TZ=Asia/Taipei"
  mongo:
    image: mongo:3.4
    restart: always
    ports:
      - "27017:27017"
    environment:
          - "TZ=Asia/Taipei"
